#!/usr/bin/env ruby
# frozen_string_literal: true

# Custom transformer: Add a header to content
# Usage in PKGBUILD: transformer: custom:transformers/add-header.rb
# Config via YAML frontmatter in source file:
#   ---
#   title: My Rule
#   ---

class Transform
  DEFAULT_HEADER = <<~HEADER
    # Agent Rule
    
    **Generated by SSoT build system**
    
    ---
    
  HEADER

  def self.transform(content, pkgname:)
    # Extract frontmatter if present
    if content.start_with?('---')
      frontmatter_end = content.index("\n---\n") || content.index("\n---")
      if frontmatter_end
        frontmatter = content[3...frontmatter_end].strip
        content = content[(frontmatter_end + 4)..] || content[(frontmatter_end + 3)..] || ''
        
        # Parse frontmatter for title
        if frontmatter =~ /title:\s*(.+)/
          title = $1.strip
          header = "#{title}\n#{'=' * title.length}\n\n#{DEFAULT_HEADER}"
          return header + content
        end
      end
    end

    # No frontmatter, use default header
    DEFAULT_HEADER + content
  end
end
